# Generated by Django 4.2.1 on 2023-07-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post", name="rating", field=models.IntegerField(default=0),
        ),
    ]
