# Generated by Django 4.2.1 on 2023-07-16 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_alter_post_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="comment_text",
            field=models.TextField(default="место для вашей рекламы"),
        ),
        migrations.AlterField(
            model_name="comment", name="rating", field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="post",
            name="post_text",
            field=models.TextField(default="место для вашей рекламы"),
        ),
    ]
