# Generated by Django 4.2.1 on 2023-07-16 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0004_rename_category_post_categories_alter_author_author_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="author", old_name="author", new_name="user",
        ),
    ]
